/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface AcpParentStreamEvents {
  created_at: number;
  event_json: string;
  run_id: string;
  seq: number;
  session_id: string;
}

export interface AuthProfileState {
  state_json: string;
  state_key: string;
  updated_at: number;
}

export interface AuthProfileStore {
  store_json: string;
  store_key: string;
  updated_at: number;
}

export interface BoardTabs {
  chat_dock: Generated<string>;
  created_by: string;
  position: number;
  revision: number;
  session_key: string;
  tab_id: string;
  title: string;
}

export interface BoardWidgets {
  content_kind: string;
  created_at: number;
  created_by: string;
  descriptor_json: string | null;
  grant_state: Generated<string>;
  granted_sha: string | null;
  html: Uint8Array | null;
  manifest: Generated<string>;
  name: string;
  position: number;
  revision: number;
  session_key: string;
  sha256: string;
  size_h: number;
  size_w: number;
  tab_id: string;
  title: string | null;
  updated_at: number;
  view_generation: string | null;
}

export interface CacheEntries {
  blob: Uint8Array | null;
  expires_at: number | null;
  key: string;
  scope: string;
  updated_at: number;
  value_json: string | null;
}

export interface ContextEngineTurnOutbox {
  advancement_key: string;
  attempt_count: Generated<number>;
  created_at: number;
  engine_id: string;
  last_attempt_at: number | null;
  last_error: string | null;
  owner_plugin_id: string | null;
  payload_json: string;
  session_id: string;
}

export interface ConversationDeliveries {
  conversation_id: string;
  created_at: number;
  message_hash: string;
  operation_id: string;
  operation_kind: string;
  platform_message_id: string | null;
  prepared_message_id: string | null;
  queue_id: string | null;
  rejection_error: string | null;
  reply_message_id: string | null;
  reply_text: string | null;
  reply_thread_id: string | null;
  reply_timestamp: number | null;
  reply_to_id: string | null;
  source_session_key: string | null;
  status: string;
  updated_at: number;
}

export interface Conversations {
  account_id: string;
  channel: string;
  conversation_id: string;
  created_at: number;
  delivery_target: string;
  kind: string;
  label: string | null;
  metadata_json: string | null;
  native_channel_id: string | null;
  native_direct_user_id: string | null;
  parent_conversation_id: string | null;
  peer_id: string;
  thread_id: string | null;
  updated_at: number;
}

export interface HeartbeatOutcomes {
  context_claimed_at: number | null;
  context_run_id: string | null;
  next_check: string | null;
  occurred_at: number;
  outcome: string;
  priority: string | null;
  response_reason: string | null;
  run_session_key: string;
  session_key: string;
  summary: string;
  task_names_json: string | null;
  updated_at: number;
  wake_reason: string | null;
  wake_source: string | null;
}

export interface MemoryAuditOutbox {
  actor_ref: string;
  agent_id: string;
  attempts: Generated<number>;
  content_hash: string | null;
  created_at: number;
  decision: string;
  delivered_at: number | null;
  event_id: string;
  intent_id: string;
  operation: string;
  reason_code: string;
  request_id: string;
  resource_revision_id: string | null;
  run_id: string;
  state: string;
  subject_ref: string;
  updated_at: number;
}

export interface MemoryChildDelegationCapabilities {
  agent_id: string;
  allowed_operations_json: string;
  capability_snapshot_id: string;
  child_session_id: string;
  child_session_identity_revision: string;
  child_subject_revision: string;
  created_at: number;
  delegation_id: string;
  expires_at: number;
  maximum_audiences_json: string;
  parent_memory_plan_id: string;
  revoked_at: number | null;
  root_principal_id: string;
  token_hash: string;
}

export interface MemoryChildDelegations {
  activated_at: number | null;
  agent_id: string;
  capability_snapshot_id: string;
  child_session_id: string;
  child_session_identity_revision: string;
  child_session_key: string;
  child_subject_revision: string;
  created_at: number;
  delegation_id: string;
  delegation_json: string;
  expires_at: number;
  parent_authority_revision: string;
  parent_facts_json: string;
  parent_session_id: string;
  parent_session_identity_revision: string;
  parent_session_key: string;
  parent_subject_revision: string;
  revoked_at: number | null;
  state: string;
}

export interface MemoryCompactionPolicies {
  compaction_policy_id: string;
  created_at: number;
  retention_state: string;
  session_id: string;
  source_policy_set_id: string;
}

export interface MemoryCompactionPolicySources {
  compaction_policy_id: string;
  created_at: number;
  delivery_audiences_json: string;
  source_event_seq: number;
  source_policy_set_id: string;
  source_session_id: string;
}

export interface MemoryEmbeddingCache {
  dims: number | null;
  embedding: string;
  hash: string;
  model: string;
  provider: string;
  provider_key: string;
  updated_at: number;
}

export interface MemoryIndexChunkProvenance {
  chunk_id: string;
  observed_at: number;
  origin_class: string;
  session_kind: string;
  supersedes_key: string | null;
}

export interface MemoryIndexChunkRecallMetadata {
  chunk_id: string;
  importance: number | null;
  project_key: string | null;
  triggers: string | null;
}

export interface MemoryIndexChunks {
  embedding: string;
  end_line: number;
  hash: string;
  id: string;
  model: string;
  path: string;
  source: Generated<string>;
  start_line: number;
  text: string;
  updated_at: number;
}

export interface MemoryIndexMeta {
  key: string;
  value: string;
}

export interface MemoryIndexSources {
  hash: string;
  id: Generated<number>;
  mtime: number;
  path: string;
  size: number;
  source: Generated<string>;
}

export interface MemoryIndexState {
  id: Generated<number>;
  revision: number;
}

export interface MemoryLineageEdges {
  child_revision_id: string;
  created_at: number;
  parent_id: string;
  parent_kind: string;
  relation_kind: string;
}

export interface MemoryMigrations {
  classification_json: string;
  cutover_at: number | null;
  migration_id: string;
  phase: string;
  plan_hash: string;
  source_hash: string;
  source_kind: string;
  updated_at: number;
  verified_at: number | null;
}

export interface MemoryPolicies {
  agent_id: string;
  created_at: number;
  current_revision_id: string;
  lifecycle_state: string;
  policy_id: string;
  revocation_epoch: Generated<number>;
  updated_at: number;
}

export interface MemoryPolicyEntries {
  audience_id: string;
  audience_kind: string;
  created_at: number;
  effect: string;
  entry_id: string;
  entry_kind: string;
  expires_at: number | null;
  grantor_principal_id: string;
  operation: string;
  policy_revision_id: string;
  principal_id: string;
  reason: string;
}

export interface MemoryPolicyRevisions {
  actor_id: string | null;
  actor_kind: string;
  created_at: number;
  lifecycle_state: string;
  policy_id: string;
  reason: string;
  revision_id: string;
  revision_number: number;
  revocation_epoch: number;
}

export interface MemoryPolicySetMembers {
  audience_intersection_json: string;
  created_at: number;
  expected_revision_id: string;
  expected_revocation_epoch: number;
  policy_id: string;
  policy_set_id: string;
  retention_state: string;
}

export interface MemoryPolicySets {
  agent_id: string;
  created_at: number;
  member_policy_set_ids_json: string;
  memory_policy_revision: string;
  policy_set_id: string;
}

export interface MemoryPostboxItems {
  agent_id: string;
  content: string;
  content_hash: string;
  created_at: number;
  item_id: string;
  purged_at: number | null;
  reviewed_at: number | null;
  reviewed_by_principal_id: string | null;
  sender_evidence_ref: string;
  source_channel_ref: string;
  source_handle_id: string;
  state: string;
  target_store_id: string;
}

export interface MemoryPostboxRateLimits {
  agent_id: string;
  deposit_count: number;
  source_channel_ref: string;
  target_store_id: string;
  updated_at: number;
  window_started_at: number;
}

export interface MemoryPostboxReviewedCopies {
  agent_id: string;
  created_at: number;
  item_id: string;
  resource_id: string;
  reviewed_content_hash: string;
  revision_id: string;
}

export interface MemoryPostboxSettings {
  agent_id: string;
  mode: string;
  target_store_id: string;
  updated_at: number;
  updated_by_principal_id: string;
}

export interface MemoryPostboxSourceHandles {
  agent_id: string;
  created_at: number;
  expires_at: number;
  sender_evidence_ref: string;
  source_channel_ref: string;
  source_handle_id: string;
  source_message_ref: string;
  source_session_id: string;
  target_store_id: string;
  used_at: number | null;
}

export interface MemoryPreoutputExposureAuthorizationFacts {
  actor_evidence_json: string;
  created_at: number;
  delegation_snapshot_json: string;
  exposure_set_id: string;
  host_facts_revision: string;
}

export interface MemoryPreoutputExposureLedger {
  agent_id: string;
  context_fingerprint: string;
  created_at: number;
  delivery_audiences_json: string;
  delivery_revision: string;
  egress_receipt_ids_json: string;
  egress_registry_revision: string;
  exposed_resource_revisions_json: string;
  exposure_receipt_ids_json: string;
  exposure_set_id: string;
  memory_policy_revision: string;
  plan_id: string;
  previous_exposure_set_id: string | null;
  revision_number: number;
  run_id: string;
  session_id: string;
  session_identity_revision: string;
  session_key: string;
  source_policy_set_ids_json: string;
  subject_revision: string;
}

export interface MemoryProjectionTargets {
  agent_id: string;
  audience_id: string;
  audience_kind: string;
  configured_by_principal_id: string;
  created_at: number;
  store_id: string;
}

export interface MemoryProjections {
  agent_id: string;
  copy_revision_id: string;
  created_at: number;
  expires_at: number | null;
  expiry_audit_reason: string | null;
  expiry_kind: string;
  preview: string;
  projection_id: string;
  publisher_principal_id: string;
  purpose: string;
  reviewed_by_principal_id: string;
  revocation_behavior: string;
  revoked_at: number | null;
  source_revision_id: string;
  state: string;
  target_audience_id: string;
  target_audience_kind: string;
  target_store_id: string;
}

export interface MemoryResourceRevisions {
  activated_at: number | null;
  actor_id: string | null;
  actor_kind: string;
  artifact_locator: string;
  content_bytes: number;
  content_hash: string;
  created_at: number;
  expires_at: number | null;
  lifecycle_state: string;
  policy_revision_id: string;
  policy_revocation_epoch: number;
  resource_id: string;
  retired_at: number | null;
  revision_id: string;
  revision_number: number;
  source_policy_set_id: string;
}

export interface MemoryResourceSubjects {
  created_at: number;
  evidence_revision: string;
  lifecycle_state: string;
  revision_id: string;
  subject_id: string;
  subject_kind: string;
}

export interface MemoryResources {
  agent_id: string;
  created_at: number;
  logical_locator: string;
  resource_id: string;
  source: Generated<string>;
  store_id: string;
}

export interface MemoryRevisionPolicyRequirements {
  created_at: number;
  expected_revision_id: string;
  expected_revocation_epoch: number;
  policy_id: string;
  requirement_kind: string;
  revision_id: string;
}

export interface MemoryRunExposureResources {
  created_at: number;
  exposure_set_id: string;
  policy_set_id: string;
  resource_revision_id: string;
}

export interface MemoryRunExposures {
  agent_id: string;
  context_fingerprint: string;
  created_at: number;
  delivery_audiences_json: string;
  delivery_revision: string;
  effective_source_policy_set_id: string;
  egress_receipt_ids_json: string;
  egress_registry_revision: string;
  exposed_resource_revisions_json: string;
  exposure_receipt_ids_json: string;
  exposure_set_id: string;
  plan_id: string;
  previous_exposure_set_id: string | null;
  revision_number: number;
  run_id: string;
  source_policy_set_ids_json: string;
}

export interface MemoryScopedChunkVectors {
  chunk_id: string;
  dims: number;
  embedding: string;
  model: string;
  updated_at: number;
}

export interface MemoryScopedChunks {
  chunk_id: string;
  chunk_key: Generated<number>;
  chunk_ordinal: number;
  content_hash: string;
  end_line: number;
  model: string;
  revision_id: string;
  start_line: number;
  text: string;
  updated_at: number;
}

export interface MemoryScopedChunksFts {
  chunk_id: string | null;
  end_line: string | null;
  revision_id: string | null;
  start_line: string | null;
  text: string | null;
}

export interface MemoryScopedChunksFtsConfig {
  k: string;
  v: string | null;
}

export interface MemoryScopedChunksFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  id: Generated<number>;
}

export interface MemoryScopedChunksFtsData {
  block: Uint8Array | null;
  id: Generated<number>;
}

export interface MemoryScopedChunksFtsDocsize {
  id: Generated<number>;
  sz: Uint8Array | null;
}

export interface MemoryScopedChunksFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface MemoryStorageRoots {
  agent_id: string;
  authority_kind: string;
  authority_owner_id: string;
  backend_kind: string;
  created_at: number;
  default_capabilities_json: string;
  lifecycle_state: string;
  opaque_locator: string;
  path_key: string | null;
  path_key_version: number;
  storage_root_id: string;
  updated_at: number;
}

export interface MemoryStores {
  agent_id: string;
  audience_id: string;
  audience_kind: string;
  created_at: number;
  lifecycle_state: string;
  policy_id: string;
  scope_kind: string;
  storage_root_id: string;
  store_id: string;
  updated_at: number;
}

export interface MemoryTranscriptExportArtifactEvents {
  created_at: number;
  event_kind: string;
  export_event_id: string;
  export_id: string;
  failure_reason: string | null;
}

export interface MemoryTranscriptExportArtifactSources {
  actor_evidence_json: string;
  created_at: number;
  delegation_snapshot_json: string;
  egress_receipt_ids_json: string;
  event_hash: string;
  event_seq: number;
  export_id: string;
  exposed_resource_revisions_json: string;
  exposure_receipt_ids_json: string;
  run_exposure_revision: number;
  run_exposure_set_id: string;
  session_identity_revision: string;
  source_event_seq: number;
  source_session_id: string;
  subject_revision: string;
}

export interface MemoryTranscriptExportArtifacts {
  artifact_content_hash: string;
  artifact_type: string;
  created_at: number;
  delivery_audiences_json: string;
  export_id: string;
  session_id: string;
  source_content_hash: string;
  source_policy_set_id: string;
}

export interface MemoryWriteIntents {
  activated_at: number | null;
  agent_id: string;
  content_bytes: number | null;
  content_hash: string | null;
  context_fingerprint: string;
  created_at: number;
  final_locator: string | null;
  idempotency_key: string;
  indexed_at: number | null;
  intent_id: string;
  mutation_id: string;
  mutation_kind: string;
  pending_revision_id: string | null;
  plan_id: string;
  request_id: string;
  resource_id: string | null;
  run_id: string;
  staged_locator: string | null;
  state: string;
  store_id: string;
  updated_at: number;
}

export interface SchemaMeta {
  agent_id: string | null;
  app_version: string | null;
  created_at: number;
  meta_key: string;
  role: string;
  schema_version: number;
  updated_at: number;
}

export interface SessionConversations {
  conversation_id: string;
  first_seen_at: number;
  last_seen_at: number;
  role: Generated<string>;
  session_id: string;
}

export interface SessionKeyContract {
  id: Generated<number>;
  main_key: string;
  updated_at: number;
}

export interface SessionMembers {
  added_at: number;
  added_by: string;
  identity_id: string;
  session_key: string;
}

export interface SessionMemorySubjectSnapshots {
  created_at: number;
  session_id: string;
  session_identity_revision: string;
  session_key: string;
  subject_revision: string;
}

export interface SessionMemorySubjects {
  binding_id: string | null;
  created_at: number;
  principal_id: string | null;
  session_key: string;
  subject_kind: string;
  subject_revision: string;
}

export interface SessionNodes {
  archived_at: number | null;
  category: string | null;
  created_actor_id: string | null;
  created_actor_type: string | null;
  created_at: number | null;
  created_via: string | null;
  current_session_id: string;
  display_name: string | null;
  entry_json: string;
  entry_valid: Generated<number>;
  fork_source_entry_id: string | null;
  fork_source_session_id: string | null;
  fork_source_session_key: string | null;
  icon: string | null;
  label: string | null;
  last_activity_at: number | null;
  last_interaction_at: number | null;
  last_read_at: number | null;
  parent_session_key: string | null;
  pinned_at: number | null;
  session_key: string;
  spawned_by: string | null;
  status: string | null;
  updated_at: number;
}

export interface SessionSuggestions {
  author_id: string;
  author_label: string | null;
  created_at: number;
  dispatch_resolution: string | null;
  dispatch_started_at: number | null;
  dispatch_token: string | null;
  id: string;
  session_key: string;
  state: string;
  text: string;
}

export interface SessionTranscriptActiveEvents {
  active_position: number;
  event_seq: number;
  message_position: number | null;
  session_id: string;
}

export interface SessionTranscriptFts {
  message_id: string | null;
  role: string | null;
  session_id: string | null;
  text: string | null;
  timestamp: string | null;
}

export interface SessionTranscriptFtsConfig {
  k: string;
  v: string | null;
}

export interface SessionTranscriptFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  id: Generated<number>;
}

export interface SessionTranscriptFtsData {
  block: Uint8Array | null;
  id: Generated<number>;
}

export interface SessionTranscriptFtsDocsize {
  id: Generated<number>;
  sz: Uint8Array | null;
}

export interface SessionTranscriptFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface SessionTranscriptIndexState {
  active_event_count: Generated<number>;
  active_message_count: Generated<number>;
  indexed_seq: number;
  leaf_event_id: string | null;
  needs_rebuild: Generated<number>;
  session_id: string;
  updated_at: number;
}

export interface SessionWindows {
  account_id: string | null;
  acp_owned: Generated<number>;
  agent_harness_id: string | null;
  channel: string | null;
  chat_type: string | null;
  created_at: number;
  display_name: string | null;
  ended_at: number | null;
  hook_external_content_source: string | null;
  model: string | null;
  model_provider: string | null;
  parent_session_key: string | null;
  plugin_owner_id: string | null;
  previous_session_id: string | null;
  primary_conversation_id: string | null;
  reason: string | null;
  session_entry_provenance: Generated<number>;
  session_id: string;
  session_key: string;
  session_scope: Generated<string>;
  spawned_by: string | null;
  started_at: number | null;
  status: string | null;
  transcript_observed_at: Generated<number | null>;
  transcript_updated_at: Generated<number | null>;
  updated_at: number;
}

export interface StandingIntents {
  channel_scope: string | null;
  cooldown_seconds: Generated<number>;
  created_at: number;
  creator_sender: string | null;
  description: string;
  expires_at: number;
  fire_count: Generated<number>;
  id: string;
  intent_key: Generated<number>;
  last_fired_at: number | null;
  max_fires: number;
  sender_scope: string | null;
  source_session_id: string | null;
  status: string;
  trigger_embedding: string | null;
  trigger_keywords: string;
}

export interface StandingIntentsFts {
  trigger_keywords: string | null;
}

export interface StandingIntentsFtsConfig {
  k: string;
  v: string | null;
}

export interface StandingIntentsFtsData {
  block: Uint8Array | null;
  id: Generated<number>;
}

export interface StandingIntentsFtsDocsize {
  id: Generated<number>;
  sz: Uint8Array | null;
}

export interface StandingIntentsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface StateLeases {
  created_at: number;
  expires_at: number | null;
  heartbeat_at: number | null;
  lease_key: string;
  owner: string;
  payload_json: string | null;
  scope: string;
  updated_at: number;
}

export interface TrajectoryRuntimeEvents {
  created_at: number;
  event_json: string;
  run_id: string | null;
  seq: number;
  session_id: string;
}

export interface TranscriptEventIdentities {
  created_at: number;
  event_id: string;
  event_type: string | null;
  message_idempotency_key: string | null;
  parent_id: string | null;
  seq: number;
  session_id: string;
}

export interface TranscriptEventMemoryPolicies {
  authorization_status: string;
  context_fingerprint: string | null;
  created_at: number;
  delivery_audiences_json: string | null;
  event_seq: number;
  run_exposure_revision: number | null;
  run_exposure_set_id: string | null;
  run_id: string | null;
  session_id: string;
  session_identity_revision: string | null;
  source_policy_set_id: string | null;
  subject_revision: string | null;
}

export interface TranscriptEventMemoryPolicyDetails {
  actor_evidence_json: string;
  created_at: number;
  delegation_snapshot_json: string;
  egress_receipt_ids_json: string;
  event_seq: number;
  exposed_resource_revisions_json: string;
  exposure_receipt_ids_json: string;
  finalized_delivery_audiences_json: string;
  normalized_audience_intersection_json: string;
  retention_state: string;
  session_id: string;
  source_event_seq: number;
  source_session_id: string;
}

export interface TranscriptEventMemoryPolicyTransitions {
  created_at: number;
  event_seq: number;
  session_id: string;
  source_event_seq: number;
  source_session_id: string;
  source_session_identity_revision: string;
  subject_revision: string;
  target_session_identity_revision: string;
  transition_kind: string;
}

export interface TranscriptEvents {
  created_at: number;
  event_json: string;
  seq: number;
  session_id: string;
}

export interface TranscriptRewriteWatermarks {
  generation: string;
  session_id: string;
  updated_at: number;
}

export interface DB {
  acp_parent_stream_events: AcpParentStreamEvents;
  auth_profile_state: AuthProfileState;
  auth_profile_store: AuthProfileStore;
  board_tabs: BoardTabs;
  board_widgets: BoardWidgets;
  cache_entries: CacheEntries;
  context_engine_turn_outbox: ContextEngineTurnOutbox;
  conversation_deliveries: ConversationDeliveries;
  conversations: Conversations;
  heartbeat_outcomes: HeartbeatOutcomes;
  memory_audit_outbox: MemoryAuditOutbox;
  memory_child_delegation_capabilities: MemoryChildDelegationCapabilities;
  memory_child_delegations: MemoryChildDelegations;
  memory_compaction_policies: MemoryCompactionPolicies;
  memory_compaction_policy_sources: MemoryCompactionPolicySources;
  memory_embedding_cache: MemoryEmbeddingCache;
  memory_index_chunk_provenance: MemoryIndexChunkProvenance;
  memory_index_chunk_recall_metadata: MemoryIndexChunkRecallMetadata;
  memory_index_chunks: MemoryIndexChunks;
  memory_index_meta: MemoryIndexMeta;
  memory_index_sources: MemoryIndexSources;
  memory_index_state: MemoryIndexState;
  memory_lineage_edges: MemoryLineageEdges;
  memory_migrations: MemoryMigrations;
  memory_policies: MemoryPolicies;
  memory_policy_entries: MemoryPolicyEntries;
  memory_policy_revisions: MemoryPolicyRevisions;
  memory_policy_set_members: MemoryPolicySetMembers;
  memory_policy_sets: MemoryPolicySets;
  memory_postbox_items: MemoryPostboxItems;
  memory_postbox_rate_limits: MemoryPostboxRateLimits;
  memory_postbox_reviewed_copies: MemoryPostboxReviewedCopies;
  memory_postbox_settings: MemoryPostboxSettings;
  memory_postbox_source_handles: MemoryPostboxSourceHandles;
  memory_preoutput_exposure_authorization_facts: MemoryPreoutputExposureAuthorizationFacts;
  memory_preoutput_exposure_ledger: MemoryPreoutputExposureLedger;
  memory_projection_targets: MemoryProjectionTargets;
  memory_projections: MemoryProjections;
  memory_resource_revisions: MemoryResourceRevisions;
  memory_resource_subjects: MemoryResourceSubjects;
  memory_resources: MemoryResources;
  memory_revision_policy_requirements: MemoryRevisionPolicyRequirements;
  memory_run_exposure_resources: MemoryRunExposureResources;
  memory_run_exposures: MemoryRunExposures;
  memory_scoped_chunk_vectors: MemoryScopedChunkVectors;
  memory_scoped_chunks: MemoryScopedChunks;
  memory_scoped_chunks_fts: MemoryScopedChunksFts;
  memory_scoped_chunks_fts_config: MemoryScopedChunksFtsConfig;
  memory_scoped_chunks_fts_content: MemoryScopedChunksFtsContent;
  memory_scoped_chunks_fts_data: MemoryScopedChunksFtsData;
  memory_scoped_chunks_fts_docsize: MemoryScopedChunksFtsDocsize;
  memory_scoped_chunks_fts_idx: MemoryScopedChunksFtsIdx;
  memory_storage_roots: MemoryStorageRoots;
  memory_stores: MemoryStores;
  memory_transcript_export_artifact_events: MemoryTranscriptExportArtifactEvents;
  memory_transcript_export_artifact_sources: MemoryTranscriptExportArtifactSources;
  memory_transcript_export_artifacts: MemoryTranscriptExportArtifacts;
  memory_write_intents: MemoryWriteIntents;
  schema_meta: SchemaMeta;
  session_conversations: SessionConversations;
  session_key_contract: SessionKeyContract;
  session_members: SessionMembers;
  session_memory_subject_snapshots: SessionMemorySubjectSnapshots;
  session_memory_subjects: SessionMemorySubjects;
  session_nodes: SessionNodes;
  session_suggestions: SessionSuggestions;
  session_transcript_active_events: SessionTranscriptActiveEvents;
  session_transcript_fts: SessionTranscriptFts;
  session_transcript_fts_config: SessionTranscriptFtsConfig;
  session_transcript_fts_content: SessionTranscriptFtsContent;
  session_transcript_fts_data: SessionTranscriptFtsData;
  session_transcript_fts_docsize: SessionTranscriptFtsDocsize;
  session_transcript_fts_idx: SessionTranscriptFtsIdx;
  session_transcript_index_state: SessionTranscriptIndexState;
  session_windows: SessionWindows;
  standing_intents: StandingIntents;
  standing_intents_fts: StandingIntentsFts;
  standing_intents_fts_config: StandingIntentsFtsConfig;
  standing_intents_fts_data: StandingIntentsFtsData;
  standing_intents_fts_docsize: StandingIntentsFtsDocsize;
  standing_intents_fts_idx: StandingIntentsFtsIdx;
  state_leases: StateLeases;
  trajectory_runtime_events: TrajectoryRuntimeEvents;
  transcript_event_identities: TranscriptEventIdentities;
  transcript_event_memory_policies: TranscriptEventMemoryPolicies;
  transcript_event_memory_policy_details: TranscriptEventMemoryPolicyDetails;
  transcript_event_memory_policy_transitions: TranscriptEventMemoryPolicyTransitions;
  transcript_events: TranscriptEvents;
  transcript_rewrite_watermarks: TranscriptRewriteWatermarks;
}
