import { createEnterpriseIdentityProviderAuthorityRegistry } from "./enterprise-identity-provider-authority-registry.js";
// Provides the empty plugin registry used before discovery completes.
import type { PluginRegistry } from "./registry-types.js";

export function createEmptyPluginRegistry(): PluginRegistry {
  const enterpriseIdentityProviderAuthorityRegistry =
    createEnterpriseIdentityProviderAuthorityRegistry();
  return {
    plugins: [],
    tools: [],
    hooks: [],
    typedHooks: [],
    channels: [],
    channelSetups: [],
    providers: [],
    modelCatalogProviders: [],
    sessionCatalogs: [],
    cliBackends: [],
    textTransforms: [],
    embeddingProviders: [],
    speechProviders: [],
    realtimeTranscriptionProviders: [],
    realtimeVoiceProviders: [],
    mediaUnderstandingProviders: [],
    transcriptSourceProviders: [],
    imageGenerationProviders: [],
    videoGenerationProviders: [],
    musicGenerationProviders: [],
    webFetchProviders: [],
    webSearchProviders: [],
    workerProviders: new Map(),
    migrationProviders: [],
    codexAppServerExtensionFactories: [],
    agentToolResultMiddlewareOwners: [],
    agentToolResultMiddlewares: [],
    memoryEmbeddingProviders: [],
    // Keep the generic registry reloadable. The authority owner publishes an
    // immutable copy when activation succeeds, rather than sharing this array.
    enterpriseIdentityProviders: [...enterpriseIdentityProviderAuthorityRegistry.providers],
    enterpriseIdentityProviderAuthorityRegistry,
    agentHarnesses: [],
    pluginRuntimeArtifacts: new Map(),
    compactionProviders: [],
    detachedTaskRuntimes: [],
    legacyInternalHooks: [],
    memoryCapabilities: [],
    memoryCorpusSupplements: [],
    memoryPromptPreparations: [],
    memoryPromptSupplements: [],
    sessionDiscussionProviders: new Map(),
    contextEngines: new Map(),
    gatewayHandlers: {},
    gatewayMethodDescriptors: [],
    dashboardDataBindings: new Map(),
    dashboardActionVerbs: new Map(),
    coreGatewayMethodNames: [],
    httpRoutes: [],
    hostedMediaResolvers: [],
    mcpServerConnectionResolvers: [],
    cliRegistrars: [],
    reloads: [],
    nodeHostCommands: [],
    nodeInvokePolicies: [],
    securityAuditCollectors: [],
    services: [],
    gatewayDiscoveryServices: [],
    commands: [],
    interactiveHandlers: [],
    sessionExtensions: [],
    trustedToolPolicies: [],
    toolMetadata: [],
    controlUiDescriptors: [],
    runtimeLifecycles: [],
    agentEventSubscriptions: [],
    sessionSchedulerJobs: [],
    sessionActions: [],
    conversationBindingResolvedHandlers: [],
    diagnostics: [],
  };
}
